server:
    logPath: "./logs"                 # 日志文件存储目录路径，建议使用绝对路径。默认为空，表示关闭
    logStdout: true               # 日志是否输出到终端。默认为true
    errorStack: true               # 当Server捕获到异常时是否记录堆栈信息到日志中。默认为true
    errorLogEnabled: true               # 是否记录异常日志信息到日志中。默认为true
    errorLogPattern: "error-{Ymd}.log"  # 异常错误日志文件格式。默认为"error-{Ymd}.log"
    accessLogEnabled: true              # 是否记录访问日志。默认为false
    accessLogPattern: "access.log" # 访问日志文件格式。默认为"access-{Ymd}.log"
    logger:
        path: "./logs"   # 日志文件路径。默认为空，表示关闭，仅输出到终端
        file: "info.log" # 日志文件格式。默认为"{Y-m-d}.log"

logger:
    path: "./logs"   # 日志文件路径。默认为空，表示关闭，仅输出到终端
    file: "info.log" # 日志文件格式。默认为"{Y-m-d}.log"
    prefix: ""            # 日志内容输出前缀。默认为空
    level: "info"         # 日志输出级别
    stdout: true          # 日志是否同时输出到终端。默认true
    rotateSize: "300M"
    RotateBackupLimit: 10
    rotateBackupExpire: "7d"            # 按照切分的文件有效期清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除

#强制指定打码代理地址，默认为空，支持热更新，xy以及自建全炸后，可以配置兜底打码地址
#ARK_PROXY : ""

# 网关鉴权key
AUTH_KEY: ""

#代理地址，可配置多个，- 地址
PROXY_URL:

#ark代理地址，可配置多个，只能v4 - 地址
ARK_PROXY_URL:

POW_URL_LIST:
  - wm-pow:8900
  
#授权码
LICENCE: ""

IQRecovery: true

#网关节点参与代理，不支持热更新
GATEWAY_ENABLE_PROXY: false

#后端预计算sentinel token 默认为false，支持热更新，开启后则为api模式，可与chat2api plus搭配使用
BackendGenSentinel: true

SentinelEndpoint: "http://wm-turnstile:3000"

# 管理后台密码
# WEB_PASSWORD: "123789"

EnableRefreshSession: true

