version: '3.8'
services:
  chatgpt-gateway-node:
    image: hanglegehang/chatgpt-gateway-node:latest
    restart: always
    ports:
      - 8100:8100
    environment:
      TZ: Asia/Shanghai # 指定时区
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./logs/:/app/logs/

    labels:
      - "com.centurylinklabs.watchtower.scope=hanglegehang-chatgpt-gateway-node"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --scope hanglegehang-chatgpt-gateway-node --cleanup --interval 600
    restart: always
    environment:
      - TZ=Asia/Shanghai
    labels:
      - "com.centurylinklabs.watchtower.scope=hanglegehang-chatgpt-gateway-node"
