version: '3.8'
services:
  chatgpt-gateway-node:
    image: hanglegehang/chatgpt-gateway-node:latest
    restart: always
    ports:
      - 8100:8100
    environment:
      TZ: Asia/Shanghai # 指定时区
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./logs/:/app/logs/
      - ./goaccess/report/:/app/resource/monitor/
    labels:
      - "com.centurylinklabs.watchtower.scope=hanglegehang-chatgpt-gateway-node"
  wm-pow:
    image: hanglegehang/wm-pow:latest
    restart: always
    # ports:
    #   - "8900:8900"
    volumes:
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
      - MaxPowThread=2
      - GIN_MODE=release
      - LOG_LEVEL=info
    labels:
      - "com.centurylinklabs.watchtower.scope=hanglegehang-chatgpt-gateway-node"
  # wm-turnstile:
  #   image: hanglegehang/wm-turnstile:latest
  #   ports:
  #     - "7200:3000"
  #   restart: always
  #   environment:
  #     - LANG=zh_CN.UTF-8
  #   labels:
  #     - "com.centurylinklabs.watchtower.scope=hanglegehang-chatgpt-gateway-node"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --scope hanglegehang-chatgpt-gateway-node --cleanup --interval 600
    restart: always
    environment:
      - TZ=Asia/Shanghai
    labels:
      - "com.centurylinklabs.watchtower.scope=hanglegehang-chatgpt-gateway-node"
